"""create finding and finding mitre mapping tables

Revision ID: 0db9628cc4fc
Revises: 873a0801082d
Create Date: 2026-07-19 16:18:20.555067

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0db9628cc4fc'
down_revision: str | None = '873a0801082d'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('primary_evidence_id', sa.Uuid(), nullable=True),
    sa.Column('primary_ioc_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='finding_severity_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('open', 'merged', 'closed', name='finding_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('p1_critical', 'p2_high', 'p3_medium', 'p4_low', name='finding_priority_enum'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('ioc_count', sa.Integer(), nullable=False),
    sa.Column('finding_data_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['primary_evidence_id'], ['evidence.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['primary_ioc_id'], ['iocs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_findings_case_id', 'findings', ['case_id'], unique=False)
    op.create_index('ix_findings_primary_evidence_id', 'findings', ['primary_evidence_id'], unique=False)
    op.create_index('ix_findings_primary_ioc_id', 'findings', ['primary_ioc_id'], unique=False)
    op.create_index('ix_findings_priority', 'findings', ['priority'], unique=False)
    op.create_index('ix_findings_severity', 'findings', ['severity'], unique=False)
    op.create_index('ix_findings_status', 'findings', ['status'], unique=False)
    op.create_table('finding_mitre_mappings',
    sa.Column('finding_id', sa.Uuid(), nullable=False),
    sa.Column('mitre_technique_id', sa.Uuid(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mapping_source', sa.String(length=64), nullable=False),
    sa.Column('attack_spec_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mitre_technique_id'], ['mitre_techniques.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finding_id', 'mitre_technique_id', name='uq_finding_mitre_mapping_pair')
    )
    op.create_index('ix_finding_mitre_mappings_finding_id', 'finding_mitre_mappings', ['finding_id'], unique=False)
    op.create_index('ix_finding_mitre_mappings_mitre_technique_id', 'finding_mitre_mappings', ['mitre_technique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_finding_mitre_mappings_mitre_technique_id', table_name='finding_mitre_mappings')
    op.drop_index('ix_finding_mitre_mappings_finding_id', table_name='finding_mitre_mappings')
    op.drop_table('finding_mitre_mappings')
    op.drop_index('ix_findings_status', table_name='findings')
    op.drop_index('ix_findings_severity', table_name='findings')
    op.drop_index('ix_findings_priority', table_name='findings')
    op.drop_index('ix_findings_primary_ioc_id', table_name='findings')
    op.drop_index('ix_findings_primary_evidence_id', table_name='findings')
    op.drop_index('ix_findings_case_id', table_name='findings')
    op.drop_table('findings')
    # ### end Alembic commands ###
