"""create evidence table

Revision ID: 20df7c637d48
Revises: 
Create Date: 2026-07-19 13:49:20.130166

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '20df7c637d48'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidence',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.Enum('ssh_auth', 'apache_access', 'apache_error', 'syslog', 'windows_event', 'json', 'csv', 'nmap_xml', 'plain_text', 'unknown', name='evidence_type_enum'), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_ref', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('encoding', sa.String(length=32), nullable=False),
    sa.Column('parser_name', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('parser_confidence', sa.Float(), nullable=True),
    sa.Column('parsed_json', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'parsed', 'failed', 'quarantined', name='evidence_status_enum'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('parsed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_case_id', 'evidence', ['case_id'], unique=False)
    op.create_index('ix_evidence_evidence_type', 'evidence', ['evidence_type'], unique=False)
    op.create_index('ix_evidence_sha256', 'evidence', ['sha256'], unique=False)
    op.create_index('ix_evidence_status', 'evidence', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evidence_status', table_name='evidence')
    op.drop_index('ix_evidence_sha256', table_name='evidence')
    op.drop_index('ix_evidence_evidence_type', table_name='evidence')
    op.drop_index('ix_evidence_case_id', table_name='evidence')
    op.drop_table('evidence')
    # ### end Alembic commands ###
