"""create vulnerabilities table

Revision ID: 4478a276c809
Revises: e20964e060ee
Create Date: 2026-07-20 03:08:39.733567

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4478a276c809'
down_revision: str | None = 'e20964e060ee'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerabilities',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('cve_id', sa.String(length=32), nullable=True),
    sa.Column('cwe_ids_json', sa.String(), nullable=True),
    sa.Column('plugin_id', sa.String(length=64), nullable=True),
    sa.Column('plugin_name', sa.String(length=512), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('asset_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('service', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('references_json', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='vulnerability_severity_enum'), nullable=False),
    sa.Column('priority', sa.Enum('p1_critical', 'p2_high', 'p3_medium', 'p4_low', name='vulnerability_priority_enum'), nullable=False),
    sa.Column('asset_criticality', sa.Enum('low', 'medium', 'high', 'critical', name='asset_criticality_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_source', sa.Enum('nessus', 'openvas', name='detection_source_enum'), nullable=False),
    sa.Column('cvss_v2_vector', sa.String(length=128), nullable=True),
    sa.Column('cvss_v2_base_score', sa.Float(), nullable=True),
    sa.Column('cvss_v3_vector', sa.String(length=128), nullable=True),
    sa.Column('cvss_v3_base_score', sa.Float(), nullable=True),
    sa.Column('cvss_v4_vector', sa.String(length=160), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('extractor_name', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'dismissed', 'false_positive', 'failed', name='vulnerability_status_enum'), nullable=False),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vulnerabilities_asset_id', 'vulnerabilities', ['asset_id'], unique=False)
    op.create_index('ix_vulnerabilities_case_id', 'vulnerabilities', ['case_id'], unique=False)
    op.create_index('ix_vulnerabilities_cve_id', 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index('ix_vulnerabilities_evidence_id', 'vulnerabilities', ['evidence_id'], unique=False)
    op.create_index('ix_vulnerabilities_priority', 'vulnerabilities', ['priority'], unique=False)
    op.create_index('ix_vulnerabilities_severity', 'vulnerabilities', ['severity'], unique=False)
    op.create_index('ix_vulnerabilities_status', 'vulnerabilities', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vulnerabilities_status', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_severity', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_priority', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_evidence_id', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_cve_id', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_case_id', table_name='vulnerabilities')
    op.drop_index('ix_vulnerabilities_asset_id', table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    # ### end Alembic commands ###
