"""create case timeline_event report tables

Revision ID: 6735a0d18bb9
Revises: 0db9628cc4fc
Create Date: 2026-07-20 01:00:39.029616

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6735a0d18bb9'
down_revision: str | None = '0db9628cc4fc'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'investigating', 'closed', name='case_status_enum'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='case_severity_enum'), nullable=False),
    sa.Column('analyst_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_analyst_id', 'cases', ['analyst_id'], unique=False)
    op.create_index('ix_cases_severity', 'cases', ['severity'], unique=False)
    op.create_index('ix_cases_status', 'cases', ['status'], unique=False)
    op.create_table('reports',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('report_type', sa.Enum('module', 'executive', name='report_type_enum'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reports_case_id', 'reports', ['case_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('case_opened', 'evidence_ingested', 'ioc_extracted', 'finding_generated', 'agent_analysis', 'case_status_changed', 'manual_note', name='timeline_event_type_enum'), nullable=False),
    sa.Column('source_finding_id', sa.Uuid(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_timeline_events_case_id', 'timeline_events', ['case_id'], unique=False)
    op.create_index('ix_timeline_events_source_finding_id', 'timeline_events', ['source_finding_id'], unique=False)
    op.create_index('ix_timeline_events_timestamp', 'timeline_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_timeline_events_timestamp', table_name='timeline_events')
    op.drop_index('ix_timeline_events_source_finding_id', table_name='timeline_events')
    op.drop_index('ix_timeline_events_case_id', table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_reports_case_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_cases_status', table_name='cases')
    op.drop_index('ix_cases_severity', table_name='cases')
    op.drop_index('ix_cases_analyst_id', table_name='cases')
    op.drop_table('cases')
    # ### end Alembic commands ###
