"""create mitre reference tables

Revision ID: 873a0801082d
Revises: d1d941bb0216
Create Date: 2026-07-19 16:17:54.440279

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873a0801082d'
down_revision: str | None = 'd1d941bb0216'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_groups',
    sa.Column('group_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attack_spec_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'attack_spec_version', name='uq_mitre_groups_id_version')
    )
    op.create_index('ix_mitre_groups_attack_spec_version', 'mitre_groups', ['attack_spec_version'], unique=False)
    op.create_index('ix_mitre_groups_group_id', 'mitre_groups', ['group_id'], unique=False)
    op.create_table('mitre_mitigations',
    sa.Column('mitigation_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attack_spec_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mitigation_id', 'attack_spec_version', name='uq_mitre_mitigations_id_version')
    )
    op.create_index('ix_mitre_mitigations_attack_spec_version', 'mitre_mitigations', ['attack_spec_version'], unique=False)
    op.create_index('ix_mitre_mitigations_mitigation_id', 'mitre_mitigations', ['mitigation_id'], unique=False)
    op.create_table('mitre_software',
    sa.Column('software_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_malware', sa.Boolean(), nullable=False),
    sa.Column('attack_spec_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('software_id', 'attack_spec_version', name='uq_mitre_software_id_version')
    )
    op.create_index('ix_mitre_software_attack_spec_version', 'mitre_software', ['attack_spec_version'], unique=False)
    op.create_index('ix_mitre_software_software_id', 'mitre_software', ['software_id'], unique=False)
    op.create_table('mitre_tactics',
    sa.Column('tactic_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shortname', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('attack_spec_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tactic_id', 'attack_spec_version', name='uq_mitre_tactics_id_version')
    )
    op.create_index('ix_mitre_tactics_attack_spec_version', 'mitre_tactics', ['attack_spec_version'], unique=False)
    op.create_index('ix_mitre_tactics_tactic_id', 'mitre_tactics', ['tactic_id'], unique=False)
    op.create_table('mitre_techniques',
    sa.Column('technique_id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tactic_shortnames_json', sa.Text(), nullable=False),
    sa.Column('platforms_json', sa.Text(), nullable=False),
    sa.Column('attack_spec_version', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('technique_id', 'attack_spec_version', name='uq_mitre_techniques_id_version')
    )
    op.create_index('ix_mitre_techniques_attack_spec_version', 'mitre_techniques', ['attack_spec_version'], unique=False)
    op.create_index('ix_mitre_techniques_technique_id', 'mitre_techniques', ['technique_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mitre_techniques_technique_id', table_name='mitre_techniques')
    op.drop_index('ix_mitre_techniques_attack_spec_version', table_name='mitre_techniques')
    op.drop_table('mitre_techniques')
    op.drop_index('ix_mitre_tactics_tactic_id', table_name='mitre_tactics')
    op.drop_index('ix_mitre_tactics_attack_spec_version', table_name='mitre_tactics')
    op.drop_table('mitre_tactics')
    op.drop_index('ix_mitre_software_software_id', table_name='mitre_software')
    op.drop_index('ix_mitre_software_attack_spec_version', table_name='mitre_software')
    op.drop_table('mitre_software')
    op.drop_index('ix_mitre_mitigations_mitigation_id', table_name='mitre_mitigations')
    op.drop_index('ix_mitre_mitigations_attack_spec_version', table_name='mitre_mitigations')
    op.drop_table('mitre_mitigations')
    op.drop_index('ix_mitre_groups_group_id', table_name='mitre_groups')
    op.drop_index('ix_mitre_groups_attack_spec_version', table_name='mitre_groups')
    op.drop_table('mitre_groups')
    # ### end Alembic commands ###
