"""create ioc table

Revision ID: d1d941bb0216
Revises: 20df7c637d48
Create Date: 2026-07-19 14:21:46.198936

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d941bb0216'
down_revision: str | None = '20df7c637d48'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iocs',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('ioc_type', sa.Enum('ipv4', 'ipv6', 'domain', 'hostname', 'url', 'email', 'sha1', 'sha256', 'md5', 'file_name', 'username', 'process_name', 'registry_key', 'port', 'service', 'mutex', 'scheduled_task', 'command_line', 'user_agent', 'certificate_fingerprint', name='ioc_type_enum'), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('raw_value', sa.String(length=2048), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'low', 'medium', 'high', 'critical', name='threat_severity_enum'), nullable=False),
    sa.Column('classification', sa.Enum('benign', 'suspicious', 'malicious', 'unknown', name='threat_category_enum'), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('rule_match_count', sa.Integer(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('extractor_name', sa.String(length=64), nullable=False),
    sa.Column('extractor_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'dismissed', 'false_positive', 'failed', name='ioc_status_enum'), nullable=False),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_iocs_case_id', 'iocs', ['case_id'], unique=False)
    op.create_index('ix_iocs_classification', 'iocs', ['classification'], unique=False)
    op.create_index('ix_iocs_evidence_id', 'iocs', ['evidence_id'], unique=False)
    op.create_index('ix_iocs_ioc_type', 'iocs', ['ioc_type'], unique=False)
    op.create_index('ix_iocs_severity', 'iocs', ['severity'], unique=False)
    op.create_index('ix_iocs_status', 'iocs', ['status'], unique=False)
    op.create_index('ix_iocs_value', 'iocs', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_iocs_value', table_name='iocs')
    op.drop_index('ix_iocs_status', table_name='iocs')
    op.drop_index('ix_iocs_severity', table_name='iocs')
    op.drop_index('ix_iocs_ioc_type', table_name='iocs')
    op.drop_index('ix_iocs_evidence_id', table_name='iocs')
    op.drop_index('ix_iocs_classification', table_name='iocs')
    op.drop_index('ix_iocs_case_id', table_name='iocs')
    op.drop_table('iocs')
    # ### end Alembic commands ###
